### ISSUE TITLE
Final evaluation indicators issue

### ISSUE THREAD

**Issue by GLL-980** [AnWang-AI/AugABSA#2]
Hello, Mr. Wang.
I followed the settings in your paper and first generated data in ASQP's rest16, with the same training batch as in your paper. Then use the enhanced data for training, and the three metrics tested in the end are significantly different from those in your paper. The attachment contains some of my parameter settings
![531$NA6BW5ZX$EYYU4EX)NC](https://github.com/user-attachments/assets/5a69dc66-84da-4443-8b6d-8d24b2049c1a)

**Comment by GLL-980** [comment]
The epoch for generating data has not been modified, and the v3 template is used. The evaluation data is like this, because there are a lot of differences, so I would like to ask for advice

#────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#       Test metric             DataLoader 0
#────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#      test quad f1          0.4658634662628174
#   test quad precision      0.4793388545513153
#    test quad recall             0.453125

**Comment by AnWang-AI** [comment]
Could you please tell me how is the performance in your experiment if you don't use the GenDA?

**Comment by GLL-980** [comment]
Hi, I think I found out what the problem is. Your source code logic should want to combine the enhanced data with rest16's train data into a train.txt for training, but I did not concatenate the enhanced data into data.list in the tuner.py file in the source code

**Comment by AnWang-AI** [comment]
I am glad to hear that you found the problem. Thanks for your concern about our work.
